export const professions = [
  {id: 0, label: 'pintor/desenhista'},
  {id: 1, label: 'carpinteiro'},
  {id: 2, label: 'cerralheiro'},
  {id: 3, label: 'canalizador'},
  {id: 4, label: 'Mecânico'},
  {id: 5, label: 'Fotógrafo'},
  {id: 6, label: 'desenvolvedor de software'},
  {id: 7, label: 'designer gráfico'},
  {id: 8, label: 'modelo'},
  {id: 9, label: 'advogado'},
  {id: 10, label: 'contabilista'},
  {id: 11, label: 'diarista'},
  {id: 12, label: 'babá'},
  {id: 13, label: 'electricista'},
  {id: 14, label: 'analista'},
  {id: 15, label: 'personal trainer'},
  {id: 16, label: 'Motorista'},
];